version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: aurora-bound-production
    networks:
      - aurora-bound
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.20.1
      FORGEVERSION: 47.4.0
      MEMORY: 8G
      MAX_PLAYERS: 6
      GUI: "false"
    ports:
      - "25565:25565"
    volumes:
      - ./:/data
      - ./mods:/data/mods
      - ./config:/data/config
      - ./logs:/data/logs
      - ./server.properties:/data/server.properties  
    restart: "no"

networks:
  aurora-bound:
    driver: bridge
